add_newline = false
continuation_prompt = ">"
format = '$time $directory $character'
right_format = '(\[${custom.jj}\])(\[${custom.git_branch}${custom.git_status}\])($username$hostname)'
command_timeout = 2000

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'

[directory]
fish_style_pwd_dir_length = 1
format = '$path'
truncate_to_repo = false

[git_branch]
format="$branch"
symbol=""
truncation_length = 15

[git_status]
modified = "U"
stashed = "*"
untracked='?'
format='(|$all_status)'

[hostname]
format='@$hostname'
trim_at='.apple.com'

[time]
disabled = false
time_format = '%R'
format='$time'

[custom.git_branch]
when = true
command = "try {jj root o+e> /dev/null } catch { starship module git_branch}"
description = "Only show git_branch if we're not in a jj repo"
format='($output)'

[custom.git_status]
when = true
command = "try {jj root o+e> /dev/null } catch { starship module git_status}"
description = "Only show git_status if we're not in a jj repo"
format='($output)'

[custom.jj]
when = "jj root --ignore-working-copy"
command='''starship-jj --ignore-working-copy starship prompt'''
format='($output)'
